apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-app.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "ml-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ml-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.frontend.name }}
